# Do not modify this file! It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations. Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "sdhci_pci" ];
  # boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  # boot.extraModulePackages = [ ];
  boot.kernelParams = [
    "mem_sleep_default=deep" # 强制使用深度睡眠模式
    "nvme.noacpi=1" # 如果使用NVMe SSD可尝试此参数
  ];

  boot.loader = {
    efi.canTouchEfiVariables = true;
    grub = {
      enable = true;
      efiSupport = true;
      devices = [ "nodev" ]; # UEFI 模式下无需指定磁盘
    };
  };

  # 已更新为 26.05 新结构
  services.logind.settings.Login = {
    HandleLidSwitch = "suspend";           # 合盖时挂起
    HandleLidSwitchDocked = "ignore";      # 连接扩展坞时忽略合盖动作
    HandleLidSwitchExternalPower = "lock"; # 外接电源时锁定
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c25da4a9-4263-4eb4-b049-ded8d08d46ad";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/88AA-51C3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # 已更新为 26.05 新结构（合并 graphics 配置）
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [ 
      intel-vaapi-driver 
      libvdpau-va-gl 
      libva-vdpau-driver 
      nvidia-vaapi-driver 
    ];
  };

  hardware.nvidia = {
    open = true;
    powerManagement = {
      enable = true;
      # finegrained = true; # 启用更细粒度的电源管理
    };
    modesetting.enable = true; # 启用内核级显示模式设置
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
}
